<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Debug-Console;Release-Console;Telemetry-Debug;Telemetry-Release</Configurations>
        <Platforms>x64;arm64</Platforms>
        <NoWarn>CA1852</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug-Console|arm64' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug-Console|x64' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release-Console|arm64' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release-Console|x64' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Telemetry-Debug|arm64' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Telemetry-Debug|x64' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Telemetry-Release|arm64' ">
      <DefineConstants>TRACE;RELEASE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Telemetry-Release|x64' ">
      <DefineConstants>TRACE;RELEASE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="NSubstitute" Version="5.3.0" />
      <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Velaptor\Velaptor.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="TimesNewRoman-Regular.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="glyph-test-data.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="stylecop.json" />
      <AdditionalFiles Include="stylecop.json" />
    </ItemGroup>

</Project>
