name: 🐛 Bug
description: File a bug.
title: "🐛"
labels: [bug, ⚕️NEEDS TRIAGE]
body:
- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: I have updated the title without removing the 🐛 emoji.
      required: true
    - label: I searched whether or not an issue already exists for the bug I encountered.
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps taken to reproduce the issue.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
    options:
    - label: Windows
    - label: Linux
    - label: Android
    - label: Mac OS
    - label: iOS
    - label: Other
  validations:
    required: true

- type: textarea
  attributes:
    label: OS Version
    description: If you know what OS version the bug occurred on, enter it here.
    placeholder: v1.2.3
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything Else
    description: Links? References? Please provide anything that will give us more context about the issue you encountered. 
    placeholder: "Tip: You can drag and drop files here (i.e. images, log files etc.)." 
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
