name: ✨ Feature Request
description: Add a new feature.
title: "✨"
labels: [✨new feature]
body:
- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: I have updated the title without removing the ✨ emoji.
      required: true
    - label: I searched whether or not a feature request already exists.
      required: true

- type: textarea
  attributes:
    label: Feature Request Purpose
    description: A clear and concise description of the problem that your feature request solves (i.e. I'm frustrated when [...] or I would like to improve [...]).
  validations:
    required: false

- type: textarea
  attributes:
    label: Solution
    description: A clear and concise description of your proposed solution.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything Else
    description: |
      Links? References? Please provide anything that will give us more context about the feature request. 
    placeholder: "Tip: You can drag and drop files here." 
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
