name: 🧪QA Testing
description: Test functionality (Project maintainers only).
title: "🧪QA Testing"
labels: ["🧪qa testing"]
body:
  - type: markdown
    attributes:
      value: "## Description:"

  - type: markdown
    attributes:
      value: Manually test the software.

  - type: checkboxes
    attributes:
      label: Complete Item Below
      options:
      - label: I have linked all issues that will be tested for this release.
        required: true

  - type: input
    id: version
    attributes:
      label: Version Being Tested
      description: |
        Add the version that will be tested for release.
        Version Format: v<major.minor.patch>[-preview.<prev-num>]
        Examples:
          v1.0.0
          v1.2.3-preview.4
    validations:
      required: true

  - type: textarea
    id: test-list
    attributes:
      label: Issues To Test
      description: A list of all the issues that will be tested.
      placeholder: |
        Example:
          - [ ] #10
          - [ ] #20
    validations:
      required: false

  - type: textarea
    id: extra-info
    attributes:
      label: Relevant Information
      description: Please enter ANY testing related information here.

  - type: textarea
    id: dependencies
    attributes:
      label: QA Testing Dependencies
      description: A list of QA testing issues that must be completed before this QA testing issue can be started.
      placeholder: |
        Example:
          - #10 
          - #20 
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
