name: 🔬 Research Item
description: Create an issue to perform research (Project maintainers only).
labels: ["🔬research"]
title: "🔬"
body:
- type: markdown
  attributes:
    value: "‼️NOTE‼️: Pull requests are not required or used for research issues."

- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have updated the title without removing the 🔬 emoji.
      required: true

- type: textarea
  attributes:
    label: What To Research
    description: A detailed description of the research to perform.
  validations:
    required: true

- type: textarea
  attributes:
    label: Research Results
    description: This can be notes, links to resources, etc.
    placeholder: "Tip: You can drag and drop files here." 
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete in order to satisfy the Definition of Done.
    value: |
      **This issue is finished when:**
      - [ ] Research complete and issues created (if needed).
      - [ ] If any issues were created, they have been added to the _**Related Work**_ section below.
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    options:
    - label: Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
    - label: Issue linked to the correct project.

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of dependencies that need to be finished first.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of related issues that are not a dependency.
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label                                                              |
      |---------------------|--------------------------------------------------------------------|
      | Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
      | Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
      | High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
