<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Platforms>x64;arm64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Velaptor\Velaptor.csproj" />
  </ItemGroup>

</Project>
