// <copyright file="KeyCodeExtensionsTests.cs" company="KinsonDigital">
// Copyright (c) KinsonDigital. All rights reserved.
// </copyright>

#pragma warning disable SA1514

namespace VelaptorTests.ExtensionMethods;

using FluentAssertions;
using Velaptor.ExtensionMethods;
using Velaptor.Input;
using Xunit;

/// <summary>
/// Tests the extension methods for the <see cref="KeyCode"/> enum.
/// </summary>
public class KeyCodeExtensionsTests
{
    #region Test Data
    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsLetterKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsLetterKeyTestData =>
        new ()
        {
            { KeyCode.A, true },
            { KeyCode.B, true },
            { KeyCode.C, true },
            { KeyCode.D, true },
            { KeyCode.E, true },
            { KeyCode.F, true },
            { KeyCode.G, true },
            { KeyCode.H, true },
            { KeyCode.I, true },
            { KeyCode.J, true },
            { KeyCode.K, true },
            { KeyCode.L, true },
            { KeyCode.M, true },
            { KeyCode.N, true },
            { KeyCode.O, true },
            { KeyCode.P, true },
            { KeyCode.Q, true },
            { KeyCode.R, true },
            { KeyCode.S, true },
            { KeyCode.T, true },
            { KeyCode.U, true },
            { KeyCode.V, true },
            { KeyCode.W, true },
            { KeyCode.X, true },
            { KeyCode.Y, true },
            { KeyCode.Z, true },
            { KeyCode.Space, true },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsNumberKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsNumberKeyTestData =>
        new ()
        {
            { KeyCode.D0, true },
            { KeyCode.D1, true },
            { KeyCode.D2, true },
            { KeyCode.D3, true },
            { KeyCode.D4, true },
            { KeyCode.D5, true },
            { KeyCode.D6, true },
            { KeyCode.D7, true },
            { KeyCode.D8, true },
            { KeyCode.D9, true },
            { KeyCode.KeyPad0, true },
            { KeyCode.KeyPad1, true },
            { KeyCode.KeyPad2, true },
            { KeyCode.KeyPad3, true },
            { KeyCode.KeyPad4, true },
            { KeyCode.KeyPad5, true },
            { KeyCode.KeyPad6, true },
            { KeyCode.KeyPad7, true },
            { KeyCode.KeyPad8, true },
            { KeyCode.KeyPad9, true },
            { KeyCode.A, false },
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsSymbolKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsSymbolKeyTestData =>
        new ()
        {
            { KeyCode.A, false },
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, true },
            { KeyCode.Equal, true },
            { KeyCode.Comma, true },
            { KeyCode.Minus, true },
            { KeyCode.Period, true },
            { KeyCode.Slash, true },
            { KeyCode.LeftBracket, true },
            { KeyCode.RightBracket, true },
            { KeyCode.Apostrophe, true },
            { KeyCode.KeyPadDivide, true },
            { KeyCode.KeyPadMultiply, true },
            { KeyCode.KeyPadSubtract, true },
            { KeyCode.KeyPadAdd, true },
            { KeyCode.KeyPadDecimal, true },
            { KeyCode.Backslash, true },
            { KeyCode.GraveAccent, true },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsVisibleKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsVisibleKeyTestData =>
        new ()
        {
            { KeyCode.A, true },
            { KeyCode.B, true },
            { KeyCode.C, true },
            { KeyCode.D, true },
            { KeyCode.E, true },
            { KeyCode.F, true },
            { KeyCode.G, true },
            { KeyCode.H, true },
            { KeyCode.I, true },
            { KeyCode.J, true },
            { KeyCode.K, true },
            { KeyCode.L, true },
            { KeyCode.M, true },
            { KeyCode.N, true },
            { KeyCode.O, true },
            { KeyCode.P, true },
            { KeyCode.Q, true },
            { KeyCode.R, true },
            { KeyCode.S, true },
            { KeyCode.T, true },
            { KeyCode.U, true },
            { KeyCode.V, true },
            { KeyCode.W, true },
            { KeyCode.X, true },
            { KeyCode.Y, true },
            { KeyCode.Z, true },
            { KeyCode.Space, true },
            { KeyCode.Unknown, false },
            { KeyCode.D0, true },
            { KeyCode.D1, true },
            { KeyCode.D2, true },
            { KeyCode.D3, true },
            { KeyCode.D4, true },
            { KeyCode.D5, true },
            { KeyCode.D6, true },
            { KeyCode.D7, true },
            { KeyCode.D8, true },
            { KeyCode.D9, true },
            { KeyCode.Semicolon, true },
            { KeyCode.Equal, true },
            { KeyCode.Comma, true },
            { KeyCode.Minus, true },
            { KeyCode.Period, true },
            { KeyCode.Slash, true },
            { KeyCode.LeftBracket, true },
            { KeyCode.RightBracket, true },
            { KeyCode.Apostrophe, true },
            { KeyCode.KeyPadDivide, true },
            { KeyCode.KeyPadMultiply, true },
            { KeyCode.KeyPadSubtract, true },
            { KeyCode.KeyPadAdd, true },
            { KeyCode.KeyPadDecimal, true },
            { KeyCode.Backslash, true },
            { KeyCode.GraveAccent, true },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, true },
            { KeyCode.KeyPad1, true },
            { KeyCode.KeyPad2, true },
            { KeyCode.KeyPad3, true },
            { KeyCode.KeyPad4, true },
            { KeyCode.KeyPad5, true },
            { KeyCode.KeyPad6, true },
            { KeyCode.KeyPad7, true },
            { KeyCode.KeyPad8, true },
            { KeyCode.KeyPad9, true },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsShiftKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsShiftKeyTestData =>
        new ()
        {
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, true },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, true },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsArrowKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsArrowKeyTestData =>
        new ()
        {
            { KeyCode.A, false },
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, true },
            { KeyCode.Left, true },
            { KeyCode.Down, true },
            { KeyCode.Up, true },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsCtrlKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsCtrlKeyTestData =>
        new ()
        {
            { KeyCode.A, false },
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, true },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, true },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.ToChar(KeyCode, bool)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool, char> ToCharTestData =>
        new ()
        {
            { KeyCode.A, true, 'A' },
            { KeyCode.A, false, 'a' },
            { KeyCode.B, true, 'B' },
            { KeyCode.B, false, 'b' },
            { KeyCode.C, true, 'C' },
            { KeyCode.C, false, 'c' },
            { KeyCode.D, true, 'D' },
            { KeyCode.D, false, 'd' },
            { KeyCode.E, true, 'E' },
            { KeyCode.E, false, 'e' },
            { KeyCode.F, true, 'F' },
            { KeyCode.F, false, 'f' },
            { KeyCode.G, true, 'G' },
            { KeyCode.G, false, 'g' },
            { KeyCode.H, true, 'H' },
            { KeyCode.H, false, 'h' },
            { KeyCode.I, true, 'I' },
            { KeyCode.I, false, 'i' },
            { KeyCode.J, true, 'J' },
            { KeyCode.J, false, 'j' },
            { KeyCode.K, true, 'K' },
            { KeyCode.K, false, 'k' },
            { KeyCode.L, true, 'L' },
            { KeyCode.L, false, 'l' },
            { KeyCode.M, true, 'M' },
            { KeyCode.M, false, 'm' },
            { KeyCode.N, true, 'N' },
            { KeyCode.N, false, 'n' },
            { KeyCode.O, true, 'O' },
            { KeyCode.O, false, 'o' },
            { KeyCode.P, true, 'P' },
            { KeyCode.P, false, 'p' },
            { KeyCode.Q, true, 'Q' },
            { KeyCode.Q, false, 'q' },
            { KeyCode.R, true, 'R' },
            { KeyCode.R, false, 'r' },
            { KeyCode.S, true, 'S' },
            { KeyCode.S, false, 's' },
            { KeyCode.T, true, 'T' },
            { KeyCode.T, false, 't' },
            { KeyCode.U, true, 'U' },
            { KeyCode.U, false, 'u' },
            { KeyCode.V, true, 'V' },
            { KeyCode.V, false, 'v' },
            { KeyCode.W, true, 'W' },
            { KeyCode.W, false, 'w' },
            { KeyCode.X, true, 'X' },
            { KeyCode.X, false, 'x' },
            { KeyCode.Y, true, 'Y' },
            { KeyCode.Y, false, 'y' },
            { KeyCode.Z, true, 'Z' },
            { KeyCode.Z, false, 'z' },
            { KeyCode.Apostrophe, true, '\"' },
            { KeyCode.Apostrophe, false, '\'' },
            { KeyCode.Semicolon, true, ':' },
            { KeyCode.Semicolon, false, ';' },
            { KeyCode.Comma, true, '<' },
            { KeyCode.Comma, false, ',' },
            { KeyCode.Period, true, '>' },
            { KeyCode.Period, false, '.' },
            { KeyCode.Slash, true, '?' },
            { KeyCode.Slash, false, '/' },
            { KeyCode.Minus, true, '_' },
            { KeyCode.Minus, false, '-' },
            { KeyCode.Equal, true, '+' },
            { KeyCode.Equal, false, '=' },
            { KeyCode.Backslash, true, '|' },
            { KeyCode.Backslash, false, '\\' },
            { KeyCode.LeftBracket, true, '{' },
            { KeyCode.LeftBracket, false, '[' },
            { KeyCode.RightBracket, true, '}' },
            { KeyCode.RightBracket, false, ']' },
            { KeyCode.D0, true, ')' },
            { KeyCode.D0, false, '0' },
            { KeyCode.D1, true, '!' },
            { KeyCode.D1, false, '1' },
            { KeyCode.D2, true, '@' },
            { KeyCode.D2, false, '2' },
            { KeyCode.D3, true, '#' },
            { KeyCode.D3, false, '3' },
            { KeyCode.D4, true, '$' },
            { KeyCode.D4, false, '4' },
            { KeyCode.D5, true, '%' },
            { KeyCode.D5, false, '5' },
            { KeyCode.D6, true, '^' },
            { KeyCode.D6, false, '6' },
            { KeyCode.D7, true, '&' },
            { KeyCode.D7, false, '7' },
            { KeyCode.D8, true, '*' },
            { KeyCode.D8, false, '8' },
            { KeyCode.D9, true, '(' },
            { KeyCode.D9, false, '9' },
            { KeyCode.GraveAccent, true, '~' },
            { KeyCode.GraveAccent, false, '`' },
            { KeyCode.KeyPad0, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad0, false, '0' },
            { KeyCode.KeyPad1, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad1, false, '1' },
            { KeyCode.KeyPad2, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad2, false, '2' },
            { KeyCode.KeyPad3, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad3, false, '3' },
            { KeyCode.KeyPad4, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad4, false, '4' },
            { KeyCode.KeyPad5, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad5, false, '5' },
            { KeyCode.KeyPad6, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad6, false, '6' },
            { KeyCode.KeyPad7, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad7, false, '7' },
            { KeyCode.KeyPad8, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad8, false, '8' },
            { KeyCode.KeyPad9, true, KeyboardKeyGroups.InvalidCharacter },
            { KeyCode.KeyPad9, false, '9' },
            { KeyCode.KeyPadDecimal, true, '.' },
            { KeyCode.KeyPadDecimal, false, '.' },
            { KeyCode.KeyPadDivide, true, '/' },
            { KeyCode.KeyPadDivide, false, '/' },
            { KeyCode.KeyPadMultiply, true, '*' },
            { KeyCode.KeyPadMultiply, false, '*' },
            { KeyCode.KeyPadSubtract, true, '-' },
            { KeyCode.KeyPadSubtract, false, '-' },
            { KeyCode.KeyPadAdd, true, '+' },
            { KeyCode.KeyPadAdd, false, '+' },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsMoveCursorKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsMoveCursorKeyTestData =>
        new ()
        {
            { KeyCode.A, false },
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, false },
            { KeyCode.Insert, false },
            { KeyCode.Delete, false },
            { KeyCode.Right, true },
            { KeyCode.Left, true },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, true },
            { KeyCode.PageDown, true },
            { KeyCode.Home, true },
            { KeyCode.End, true },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };

    /// <summary>
    /// Gets the data for testing the <see cref="KeyCodeExtensions.IsDeletionKey(KeyCode)"/> method.
    /// </summary>
    public static TheoryData<KeyCode, bool> IsDeletionKeyTestData =>
        new ()
        {
            { KeyCode.A, false },
            { KeyCode.B, false },
            { KeyCode.C, false },
            { KeyCode.D, false },
            { KeyCode.E, false },
            { KeyCode.F, false },
            { KeyCode.G, false },
            { KeyCode.H, false },
            { KeyCode.I, false },
            { KeyCode.J, false },
            { KeyCode.K, false },
            { KeyCode.L, false },
            { KeyCode.M, false },
            { KeyCode.N, false },
            { KeyCode.O, false },
            { KeyCode.P, false },
            { KeyCode.Q, false },
            { KeyCode.R, false },
            { KeyCode.S, false },
            { KeyCode.T, false },
            { KeyCode.U, false },
            { KeyCode.V, false },
            { KeyCode.W, false },
            { KeyCode.X, false },
            { KeyCode.Y, false },
            { KeyCode.Z, false },
            { KeyCode.Space, false },
            { KeyCode.Unknown, false },
            { KeyCode.Apostrophe, false },
            { KeyCode.Comma, false },
            { KeyCode.Minus, false },
            { KeyCode.Period, false },
            { KeyCode.Slash, false },
            { KeyCode.D0, false },
            { KeyCode.D1, false },
            { KeyCode.D2, false },
            { KeyCode.D3, false },
            { KeyCode.D4, false },
            { KeyCode.D5, false },
            { KeyCode.D6, false },
            { KeyCode.D7, false },
            { KeyCode.D8, false },
            { KeyCode.D9, false },
            { KeyCode.Semicolon, false },
            { KeyCode.Equal, false },
            { KeyCode.LeftBracket, false },
            { KeyCode.Backslash, false },
            { KeyCode.RightBracket, false },
            { KeyCode.GraveAccent, false },
            { KeyCode.Escape, false },
            { KeyCode.Enter, false },
            { KeyCode.Tab, false },
            { KeyCode.Backspace, true },
            { KeyCode.Insert, false },
            { KeyCode.Delete, true },
            { KeyCode.Right, false },
            { KeyCode.Left, false },
            { KeyCode.Down, false },
            { KeyCode.Up, false },
            { KeyCode.PageUp, false },
            { KeyCode.PageDown, false },
            { KeyCode.Home, false },
            { KeyCode.End, false },
            { KeyCode.CapsLock, false },
            { KeyCode.ScrollLock, false },
            { KeyCode.NumLock, false },
            { KeyCode.PrintScreen, false },
            { KeyCode.Pause, false },
            { KeyCode.F1, false },
            { KeyCode.F2, false },
            { KeyCode.F3, false },
            { KeyCode.F4, false },
            { KeyCode.F5, false },
            { KeyCode.F6, false },
            { KeyCode.F7, false },
            { KeyCode.F8, false },
            { KeyCode.F9, false },
            { KeyCode.F10, false },
            { KeyCode.F11, false },
            { KeyCode.F12, false },
            { KeyCode.F13, false },
            { KeyCode.F14, false },
            { KeyCode.F15, false },
            { KeyCode.F16, false },
            { KeyCode.F17, false },
            { KeyCode.F18, false },
            { KeyCode.F19, false },
            { KeyCode.F20, false },
            { KeyCode.F21, false },
            { KeyCode.F22, false },
            { KeyCode.F23, false },
            { KeyCode.F24, false },
            { KeyCode.F25, false },
            { KeyCode.KeyPad0, false },
            { KeyCode.KeyPad1, false },
            { KeyCode.KeyPad2, false },
            { KeyCode.KeyPad3, false },
            { KeyCode.KeyPad4, false },
            { KeyCode.KeyPad5, false },
            { KeyCode.KeyPad6, false },
            { KeyCode.KeyPad7, false },
            { KeyCode.KeyPad8, false },
            { KeyCode.KeyPad9, false },
            { KeyCode.KeyPadDecimal, false },
            { KeyCode.KeyPadDivide, false },
            { KeyCode.KeyPadMultiply, false },
            { KeyCode.KeyPadSubtract, false },
            { KeyCode.KeyPadAdd, false },
            { KeyCode.KeyPadEnter, false },
            { KeyCode.KeyPadEqual, false },
            { KeyCode.LeftShift, false },
            { KeyCode.LeftControl, false },
            { KeyCode.LeftAlt, false },
            { KeyCode.LeftSuper, false },
            { KeyCode.RightShift, false },
            { KeyCode.RightControl, false },
            { KeyCode.RightAlt, false },
            { KeyCode.RightSuper, false },
            { KeyCode.Menu, false },
        };
    #endregion

    [Theory]
    [MemberData(nameof(IsLetterKeyTestData))]
    public void IsLetterKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsLetterKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsNumberKeyTestData))]
    public void IsNumberKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsNumberKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsSymbolKeyTestData))]
    public void IsSymbolKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsSymbolKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsVisibleKeyTestData))]
    public void IsVisibleKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsVisibleKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsShiftKeyTestData))]
    public void IsShiftKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsShiftKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsArrowKeyTestData))]
    public void IsArrowKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsArrowKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsCtrlKeyTestData))]
    public void IsCtrlKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsCtrlKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(ToCharTestData))]
    public void ToChar_WhenAnyShiftKeyDownInvoked_ReturnsCorrectResult(KeyCode key, bool anyShiftKeysDown, char expected)
    {
        // Arrange & Act
        var actual = key.ToChar(anyShiftKeysDown);

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsMoveCursorKeyTestData))]
    public void IsMoveCursorKeyTestData_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsMoveCursorKey();

        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [MemberData(nameof(IsDeletionKeyTestData))]
    public void IsDeletionKey_WhenInvoked_ReturnsCorrectResult(KeyCode key, bool expected)
    {
        // Arrange & Act
        var actual = key.IsDeletionKey();

        // Assert
        actual.Should().Be(expected);
    }
}
