trigger:
  branches:
    include:
    - develop # Development Environment
    - master # Production Environment


variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'any'
- name: buildConfiguration
  ${{ if notIn(variables['Build.SourceBranchName'], 'develop', 'master')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'master')}}:
    value: 'Release'
- name: coverageReportDirName
  value: 'CoverageReport'
- name: projectName
  value: 'Raptor'
- name: kinsonDigitalNugetFeed
  value: '1020f331-f22a-4330-a69a-78abfe6f6372/4c644bf2-f1e8-4f28-a3df-3bc9d3283df9'    
- name: pool
  value: 'KinsonServer'




stages:
- stage: 'Main_Stage' #🟢
  displayName: 'Main Stage'
  pool: '$(pool)'
  jobs:
  - job: 'Build_Raptor_Job' #🟠
    displayName: 'Build Raptor'
    steps:
    - template: templates/build-tasks-template.yml
      parameters:
        projectName: $(projectName)
        buildPlatform: $(buildPlatform)
        buildConfiguration: $(buildConfiguration)
        vstsFeed: '$(kinsonDigitalNugetFeed)'


  - job: 'Run_Raptor_Tests_Job' #🟠
    displayName: 'Run Raptor Tests'
    steps:
    - template: templates/test-tasks-template.yml
      parameters:
        projectName: $(projectName)
        buildPlatform: $(buildPlatform)      
        buildConfiguration: $(buildConfiguration)
        vstsFeed: '$(kinsonDigitalNugetFeed)'


  - job: 'Publish_Raptor_Artifacts_Job' #🟠
    displayName: 'Publish Raptor Artifacts'
    steps:
    - template: templates/publish-tasks-template.yml
      parameters:
        projectName: $(projectName)
        buildPlatform: $(buildPlatform)
        buildConfiguration: $(buildConfiguration)
        vstsFeed: '$(kinsonDigitalNugetFeed)'
