name: ✅Build Status Check
run-name: ✅Build Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  build_velaptor:
    name: Build Velaptor Status Check
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        build_config: [Debug, Telemetry-Debug]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj" -c ${{ matrix.build_config }};


  build_velaptor_testing:
    name: Build Velaptor Testing Status Check
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/Testing/${{ vars.PROJECT_NAME }}Testing/${{ vars.PROJECT_NAME }}Testing.csproj" -c Debug;


  build_avalonia_testing:
    name: Build Avalonia Testing Status Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/Testing/AvaloniaTesting/AvaloniaTesting.csproj" -c Debug;


  build_playground:
    name: Build Playground Status Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/Testing/PlaygroundApp/PlaygroundApp.csproj" -c Debug;


  build_keyboard_perf:
    name: Build Keyboard Performance Status Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/Performance/KeyboardPerf/KeyboardPerf.csproj" -c Debug;


  build_measure_text_perf:
    name: Build Measure Text Performance Status Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/Performance/MeasureTextPerf/MeasureTextPerf.csproj" -c Debug;


  build_mouse_perf:
    name: Build Mouse Performance Status Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/Performance/MousePerf/MousePerf.csproj" -c Debug;
