name: ✅ Build Sample Projects Status Check


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  pull_request: 
    branches: [main, preview]


jobs:
  build_sample_projects:
    name: Build Sample Projects
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Velaptor (for composite action)
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build
      uses: ./.github/actions/build-target-projects
      with:
        target-solution-name: "SampleProjects"
        target-owner-name: "KinsonDigital"
        target-repo-name: "VelaptorDocs"
        target-ref: "main"
        target-relative-dir-path: "SampleProjects"
        velaptor-branch: "${{ github.head_ref }}"
        dotnet-sdk-version: "${{ vars.NET_SDK_VERSION }}"
        deno-version: "${{ vars.DENO_VERSION }}"
