name: ✅ Build Velaptor Aseprite Status Check


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  pull_request: 
    branches: [main, preview]


jobs:
  build_velaptor_aseprite:
    name: Build Velaptor Aseprite
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Velaptor (for composite action)
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Build
      uses: ./.github/actions/build-target-projects
      with:
        target-solution-name: "VelaptorAseprite"
        target-owner-name: "KinsonDigital"
        target-repo-name: "VelaptorAseprite"
        target-ref: "main"
        velaptor-branch: "${{ github.ref_name }}"
        dotnet-sdk-version: "${{ vars.NET_SDK_VERSION }}"
        deno-version: "${{ vars.DENO_VERSION }}"
