name: ✅ CICD Build Status Check
run-name: ✅ CICD Build Status Check (${{ github.base_ref }} branch)


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  build:
    name: CICD Build Status Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Up Deno (${{ vars.DENO_VERSION }})
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.0
        with:
          deno-version: "${{ vars.DENO_VERSION }}"

      - name: Build Scripts
        run: deno check .github/cicd-scripts/**/*.ts;
