name: 🚀 Release
run-name: ${{ vars.PROJECT_NAME }} ${{ inputs.release-type }} Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}


permissions: {} # Set the permissions to an empty object to prevent the workflow from having any permissions by default.


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
    inputs:
      release-type:
        description: The type of release. Choose 'Preview' or 'Production'.
        required: true
        type: choice
        options: [Preview, Production]
      trigger-docs-release:
        description: Trigger Velaptor docs release workflow after the library release is done. Only applicable for production releases.
        required: false
        default: true
        type: boolean
      cache-disabled:
        description: Cache Disabled - Check to disable caching for the workflow.
        required: false
        default: false
        type: boolean
      dry-run:
        description: Dry Run - Check to run the workflow without creating a release.
        required: false
        default: false
        type: boolean


jobs:
  get_and_validate_version:
    name: Get And Validate Version
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get Version
        id: get-version
        uses: KinsonDigital/Infrastructure/actions/get-version@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          version-file-path: "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj"
          cache-enabled: ${{ inputs.cache-disabled == true && 'false' || 'true' }}

      - name: Validate Version
        id: validate-version
        uses: KinsonDigital/Infrastructure/actions/validate-version@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          version: "v${{ steps.get-version.outputs.version }}"
          release-type: "${{ inputs.release-type }}"
          cache-enabled: ${{ inputs.cache-disabled == true && 'false' || 'true' }}


  validate_release:
    name: Validate Release
    needs: [get_and_validate_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/validate-release.yml@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
    with:
      owner-name: "${{ vars.ORGANIZATION_NAME }}"
      repo-name: "${{ vars.PROJECT_NAME }}"
      release-type: "${{ inputs.release-type }}"
      version: "${{ needs.get_and_validate_version.outputs.version }}"
      relative-release-notes-file-path: "ReleaseNotes/${{ inputs.release-type }}Releases/${{ vars.RELEASE_NOTES_FILE_NAME_PREFIX }}${{ needs.get_and_validate_version.outputs.version }}.md"
      is-dotnet-project: true
    secrets:
      cicd-pat: "${{ secrets.CICD_TOKEN }}"


  build_velaptor:
    name: Build Velaptor
    needs: [get_and_validate_version, validate_release]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2025, ubuntu-24.04, macos-26]
        build_config: [Debug, Telemetry-Debug, Release, Telemetry-Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj" -c ${{ matrix.build_config }};


  # Ensure that the sample projects in the VelaptorDocs repo build
  build_sample_projects:
    name: Build Sample Projects
    runs-on: ubuntu-24.04
    steps:
      - name: Build VelaptorDocs Sample Projects
        uses: ./.github/actions/build-target-projects
        with:
          target-solution-name: "VelaptorDocs"
          target-owner-name: "KinsonDigital"
          target-repo-name: "VelaptorDocs"
          target-ref: "main"
          target-relative-dir-path: "SampleProjects"
          velaptor-branch: "${{ github.ref_name }}"
          dotnet-sdk-version: "${{ vars.NET_SDK_VERSION }}"
          deno-version: "${{ vars.DENO_VERSION }}"


  # Ensure that the VelaptorTemplates project builds
  build_velaptor_templates:
    name: Build Velaptor Templates
    runs-on: ubuntu-24.04
    steps:
      - name: Build VelaptorDocs Sample Projects
        uses: ./.github/actions/build-target-projects
        with:
          target-solution-name: "VelaptorTemplates"
          target-owner-name: "KinsonDigital"
          target-repo-name: "VelaptorTemplates"
          target-ref: "main"
          velaptor-branch: "${{ github.ref_name }}"
          dotnet-sdk-version: "${{ vars.NET_SDK_VERSION }}"
          deno-version: "${{ vars.DENO_VERSION }}"


  # Ensure that the VelaptorAseprite project builds
  build_velaptor_aseprite:
    name: Build Velaptor Aseprite
    runs-on: ubuntu-24.04
    steps:
      - name: Build VelaptorDocs Sample Projects
        uses: ./.github/actions/build-target-projects
        with:
          target-solution-name: "VelaptorAseprite"
          target-owner-name: "KinsonDigital"
          target-repo-name: "VelaptorAseprite"
          target-ref: "main"
          velaptor-branch: "${{ github.ref_name }}"
          dotnet-sdk-version: "${{ vars.NET_SDK_VERSION }}"
          deno-version: "${{ vars.DENO_VERSION }}"


  run_tests:
    name: Run Unit Tests
    needs: [get_and_validate_version, validate_release]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2025, ubuntu-24.04, macos-26]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Tests
        run: |
          dotnet test "${{ github.workspace }}/Testing/${{ vars.PROJECT_NAME }}Tests/${{ vars.PROJECT_NAME }}Tests.csproj" `
            -c ${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }};


  perform_release:
    name: Perform ${{ inputs.release-type }} Release
    needs: [get_and_validate_version, validate_release, build_velaptor,
      build_sample_projects, build_velaptor_templates, build_velaptor_aseprite,
      run_tests]
    uses: KinsonDigital/Infrastructure/.github/workflows/dotnet-lib-release.yml@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
    with:      
      owner-name: "${{ vars.ORGANIZATION_NAME }}" 
      repo-name: "${{ vars.PROJECT_NAME }}"
      project-name: "${{ vars.PROJECT_NAME }}"
      release-type: "${{ inputs.release-type }}"
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
      build-config: ${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }}
      version: ${{ needs.get_and_validate_version.outputs.version }}
      transpile-readme: true
      dry-run: ${{ inputs.dry-run }}
      relative-release-notes-file-path: "ReleaseNotes/${{ inputs.release-type }}Releases/${{ vars.RELEASE_NOTES_FILE_NAME_PREFIX }}${{ needs.get_and_validate_version.outputs.version }}.md"
    secrets: 
      cicd-pat: "${{ secrets.CICD_TOKEN }}"
      nuget-api-key: "${{ secrets.NUGET_ORG_API_KEY }}"


  # Execute the full Velaptor docs release workflow after the library release is done.
  release_velaptor_docs:
    name: Release Velaptor Docs
    runs-on: ubuntu-24.04
    needs: [get_and_validate_version, validate_release, build_velaptor,
      build_sample_projects, build_velaptor_templates, build_velaptor_aseprite,
      run_tests, perform_release]
    if: ${{ inputs.dry-run == false && inputs.trigger-docs-release == true }}
    steps:
      - name: Execute Release
        env:
          VERSION: "v${{ needs.get_and_validate_version.outputs.version }}"
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
        run: |
          $workflowName = "${{ vars.VELAPTOR_DOCS_FULL_RELEASE_WORKFLOW_NAME }}";
          $orgName = "${{ vars.ORGANIZATION_NAME }}";
          $repoName = "${{ vars.VELAPTOR_DOCS_REPO_NAME }}";
          $docSiteReleaseBranch = "${{ vars.DOC_SITE_RELEASE_BRANCH }}";
          $version = $env:VERSION;

          gh workflow run $workflowName -R "$orgName/$repoName" --ref "$docSiteReleaseBranch" --field "api-version=$version" --field "executed-externally=true";


  send_release_announcements:
    name: Send Release Announcements
    runs-on: ubuntu-24.04
    needs: [get_and_validate_version, validate_release, build_velaptor,
      build_sample_projects, build_velaptor_templates, build_velaptor_aseprite,
      run_tests, perform_release]
    if: ${{ inputs.dry-run == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Send X Release Announcement
        uses: KinsonDigital/Infrastructure/actions/send-x-release-announcement@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        continue-on-error: true
        with:
          repo-owner: ${{ vars.ORGANIZATION_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          version: ${{ needs.get_and_validate_version.outputs.version }}
          website-url: ${{ vars.WEBSITE_URL }}
          local-post-template-file-path: "${{ github.workspace }}/templates/release-announcement.txt"
          discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
          access-token-key: ${{ secrets.X_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          consumer-api-key: ${{ secrets.X_CONSUMER_API_KEY }}
          consumer-api-secret: ${{ secrets.X_CONSUMER_API_SECRET }}
          cache-enabled: ${{ inputs.cache-disabled == true && 'false' || 'true' }}
          github-token: ${{ secrets.CICD_TOKEN }}

      - name: Send Bluesky Release Announcement
        uses: KinsonDigital/Infrastructure/actions/send-bluesky-release-announcement@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          repo-owner: ${{ vars.ORGANIZATION_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          version: ${{ needs.get_and_validate_version.outputs.version }}
          website-url: ${{ vars.WEBSITE_URL }}
          local-post-template-file-path: "${{ github.workspace }}/templates/release-announcement.txt"
          discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
          service: ${{ vars.BLUESKY_SERVICE }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          cache-enabled: ${{ inputs.cache-disabled == true && 'false' || 'true' }}
          github-token: ${{ secrets.CICD_TOKEN }}


  process_milestone:
    name: Process Milestone ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
    needs: [get_and_validate_version, validate_release, build_velaptor, build_sample_projects,
      build_velaptor_aseprite, build_velaptor_templates, perform_release]
    if: ${{ inputs.dry-run == false }}
    uses: KinsonDigital/Infrastructure/.github/workflows/process-milestone.yml@acc7aa3997697717943e56c439f7b529d1e1d1ba # v19.0.0
    with:
      owner-name: ${{ vars.ORGANIZATION_NAME }}
      repo-name: ${{ vars.PROJECT_NAME }}
      version: ${{ needs.get_and_validate_version.outputs.version }}
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}
