name: 🚀Release
run-name: ${{ vars.PROJECT_NAME }} ${{ inputs.release-type }} Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
    inputs:
      release-type:
        description: The type of release.  Choose 'Preview' or 'Production'.
        required: true
        type: choice
        options: [Preview, Production]
      trigger-docs-release:
        description: Trigger Velaptor docs release workflow after the library release is done. Only applicable for production releases.
        required: false
        default: true
        type: boolean
      dry-run:
        description: Dry Run - Check to run the workflow without creating a release.
        required: false
        default: false
        type: boolean

# Set the permissions to an empty object to prevent the workflow from having any permissions by default.
permissions: {}


jobs:
  validate_branch:
    name: Validate Branch
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          PROD_BRANCH: ${{ vars.PROD_BRANCH }}
          PREV_BRANCH: ${{ vars.PREV_BRANCH }}
          RELEASE_TYPE: ${{ inputs.release-type }}
        run: |
          $releaseType = $env:RELEASE_TYPE.ToLower();
          $branchName = $env:BRANCH_NAME.Trim();
          $expectedBranchName = $env:RELEASE_TYPE -eq "production" ? $env:PROD_BRANCH : $env:PREV_BRANCH;
          $errorMsg = "::error::The branch name must be '$branchName' for a $releaseType release.";

          if ($releaseType -eq "preview") {
            if ($branchName -ne $expectedBranchName) {
              Write-Host $errorMsg;
              exit "${{ inputs.dry-run }}" -eq "true" ? 0 : 1;
            }
          } elseif ($releaseType -eq "production") {
            if ($branchName -ne $expectedBranchName) {
              Write-Host $errorMsg;
              exit "${{ inputs.dry-run }}" -eq "true" ? 0 : 1;
            }
          }


  determine_release_notes_path:
    name: Determine Release Notes Dir Path
    runs-on: ubuntu-latest
    outputs:
      release-notes-dir-path: ${{ steps.get-dir-path.outputs.release-notes-dir-path }}
    steps:
      - name: Get Dir Path
        id: get-dir-path
        run: |
          $dirPath = "${{ inputs.release-type }}" -eq "Production" ? "${{ vars.PROD_RELATIVE_RELEASE_NOTES_DIR_PATH }}" : "${{ vars.PREV_RELATIVE_RELEASE_NOTES_DIR_PATH }}";
          "release-notes-dir-path=$dirPath" >> $env:GITHUB_OUTPUT;


  get_and_validate_version:
    name: Get And Validate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get Version
        id: get-version
        uses: KinsonDigital/Infrastructure/actions/get-version@f141c7680f051d4c2b03c4672b8fddbf7bda4a5e #v17.2.0
        with:
          version-file-path: "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj"

      - name: Validate Version
        uses: KinsonDigital/Infrastructure/actions/validate-version@f141c7680f051d4c2b03c4672b8fddbf7bda4a5e #v17.2.0
        with:
          version: "v${{ steps.get-version.outputs.version }}"
          release-type: "${{ inputs.release-type }}"


  # Build with preview/debug build configs
  build:
    name: Build Velaptor
    needs: [validate_branch, get_and_validate_version]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        build_config: [Debug, Telemetry-Debug, Release, Telemetry-Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        run: dotnet build "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj" -c ${{ matrix.build_config }};


  run_tests:
    name: Run Unit Tests
    needs: [validate_branch, get_and_validate_version]
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
          - platform: "ubuntu-latest"
          - platform: "macos-latest" # ARM-based (M1 and above).
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Tests
        run: |
          dotnet test "${{ github.workspace }}/Testing/${{ vars.PROJECT_NAME }}Tests/${{ vars.PROJECT_NAME }}Tests.csproj" `
            -c ${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }};


  run_release:
    name: Performing ${{ inputs.release-type }} Release of ${{ vars.PROJECT_NAME }} (${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }})
    needs: [validate_branch, get_and_validate_version, determine_release_notes_path, build, run_tests]
    uses: KinsonDigital/Infrastructure/.github/workflows/dotnet-lib-release.yml@f141c7680f051d4c2b03c4672b8fddbf7bda4a5e #v17.2.0
    with:
      project-name: "${{ vars.PROJECT_NAME}}"
      release-type: "${{ inputs.release-type }}"
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
      release-notes-file-path: "${{ needs.determine_release_notes_path.outputs.release-notes-dir-path }}/${{ vars.RELEASE_NOTES_FILE_NAME_PREFIX }}v${{ needs.get_and_validate_version.outputs.version }}.md"
      build-config: ${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }}
      build-project: false
      dry-run: ${{ inputs.dry-run }}
      transpile-readme: true
      deno-version: "${{ vars.DENO_VERSION }}"
      telemetry-enabled: true
    secrets:
        cicd-pat: "${{ secrets.CICD_TOKEN }}"
        nuget-org-api-key: "${{ secrets.NUGET_ORG_API_KEY }}"
        telemetry-key: "${{ secrets.TELEMETRY_KEY }}"


  # Execute the full Velaptor docs release workflow after the library release is done.
  release_velaptor_docs:
    name: Release Velaptor Docs
    runs-on: ubuntu-latest
    needs: [validate_branch, get_and_validate_version, determine_release_notes_path, build, run_tests, run_release]
    if: ${{ inputs.release-type == 'Production' && inputs.dry-run == false && inputs.trigger-docs-release == true }}
    steps:
      - name: Execute Release
        env:
          VERSION: "v${{ needs.get_and_validate_version.outputs.version }}"
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
        run: |
          $workflowName = "${{ vars.VELAPTOR_DOCS_FULL_RELEASE_WORKFLOW_NAME }}";
          $orgName = "${{ vars.ORGANIZATION_NAME }}";
          $repoName = "${{ vars.VELAPTOR_DOCS_REPO_NAME }}";
          $docSiteReleaseBranch = "${{ vars.DOC_SITE_RELEASE_BRANCH }}";
          $version = $env:VERSION;

          gh workflow run $workflowName -R "$orgName/$repoName" --ref "$docSiteReleaseBranch" --field "api-version=$version" --field "executed-externally=true";


  send_release_announcements:
    name: Send Release Announcements
    runs-on: ubuntu-latest
    needs: [validate_branch, get_and_validate_version, determine_release_notes_path, build, run_tests, run_release]
    if: ${{ inputs.release-type == 'Production' && inputs.dry-run == false }}
    steps:
      - name: Send X Release Announcement
        uses: KinsonDigital/Infrastructure/actions/send-x-release-announcement@f141c7680f051d4c2b03c4672b8fddbf7bda4a5e #v17.2.0
        with:
          repo-owner: ${{ vars.ORGANIZATION_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          version: ${{ needs.get_and_validate_version.outputs.version }}
          website-url: ${{ vars.WEBSITE_URL }}
          local-post-template-file-path: "${{ github.workspace }}/templates/release-announcement.txt"
          discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
          access-token-key: ${{ secrets.X_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          consumer-api-key: ${{ secrets.X_CONSUMER_API_KEY }}
          consumer-api-secret: ${{ secrets.X_CONSUMER_API_SECRET }}
          github-token: ${{ secrets.CICD_TOKEN }}

      - name: Send Bluesky Release Announcement
        uses: KinsonDigital/Infrastructure/actions/send-bluesky-release-announcement@f141c7680f051d4c2b03c4672b8fddbf7bda4a5e #v17.2.0
        with:
          repo-owner: ${{ vars.ORGANIZATION_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          version: ${{ needs.get_and_validate_version.outputs.version }}
          website-url: ${{ vars.WEBSITE_URL }}
          local-post-template-file-path: "${{ github.workspace }}/templates/release-announcement.txt"
          discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
          service: ${{ vars.BLUESKY_SERVICE }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password:  ${{ secrets.BLUESKY_PASSWORD }}
          github-token: ${{ secrets.CICD_TOKEN }}
