name: 🧪 Test Sample Projects


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  test_sample_projects:
    name: Test Sample Projects
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Velaptor (for composite action)
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Build VelaptorDocs Sample Projects
      uses: ./.github/actions/build-target-projects
      with:
        target-solution-name: "VelaptorAseprite"
        target-owner-name: "KinsonDigital"
        target-repo-name: "VelaptorAseprite"
        target-ref: "main"
        # target-relative-dir-path: "SampleProjects"
        velaptor-branch: "${{ github.ref_name }}"
        dotnet-sdk-version: "${{ vars.NET_SDK_VERSION }}"
        deno-version: "${{ vars.DENO_VERSION }}"
