name: ✅ SDK Status Check
run-name: ✅ SDK Status Check (${{ github.base_ref }} branch)


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  sdk_status_check:
    name: ${{ vars.PROJECT_NAME }} SDK Status Check
    runs-on: ubuntu-24.04
    steps:
      - name: Validate SDK Versions
        uses: KinsonDigital/Infrastructure/actions/validate-sdk-versions@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          base-search-dir-path: "${{ github.workspace }}"
          net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
