name: ✅SDK Status Check
run-name: ✅SDK Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  sdk_status_check:
    name: ${{ vars.PROJECT_NAME }} SDK Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Validate SDK Versions
        uses: KinsonDigital/Infrastructure/actions/validate-sdk-versions@7461c11f3d9c3f6e0eaf9047e4d6bd9ac36a26ba # v18.0.0
        with:
          base-search-dir-path: "${{ github.workspace }}"
          net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
