name: If Expressing Testing

on:
  workflow_dispatch:
  push:
    branches: [ his-branch ]
  # pull_request:
  #   types: [ synchronize ]
  #   branches: [ develop ]

jobs:
  If_Expression_Testing:
    name: Preview Unit Testing Status Check
    runs-on: windows-latest
    env:
      MYVAR: MyValue
    steps:
    - uses: actions/checkout@v2

    # github.base_ref is the target branch that the pull request is going to
    # github.head_ref is the source branch of the branch being merged into the target

    - name: Env Var Before Change
      run: echo "MYVAR Value - ${{ env.MYVAR }}"

    - name: List All Environment Variables
      run: "[System.Environment]::GetEnvironmentVariables()"

    - name: Update Variable Value
      run: echo "MYVAR=NewValue" >> $GITHUB_MYVAR

    - name: Env Var After Change
      run: echo "MYVAR Value - ${{ env.MYVAR }}"
# --------------------------------------------------------------------------------
# PULL REQUEST BRANCH TESTING

    # - name: Branches
    #   run: echo "Ref - ${{ github.ref }} | Head Ref - ${{ github.head_ref }} | Base Ref - ${{ github.base_ref }}"

    # - name: If His Branch
    #   if: ${{ github.base_ref == 'develop' }}
    #   run: echo "THIS IS HIS BRANCH!!!"

    # - name: If Her Branch
    #   if: ${{ github.base_ref == 'master' }}
    #   run: echo "THIS IS HER BRANCH!!!"
