name: 🧪 Workflow Testing 🧪

on:
  workflow_dispatch:
  # push:
  #   branches: [ preview/v1.0.0-preview.1 ]

jobs:
  Test_Job:
    name: Test Job
    runs-on: windows-latest
    # environment: preview # TODO: Test this with variable values and if expressions
    steps:
    - name: Print Branch Name
      run: echo "Branch - ${{ github.ref }}"

    - name: Set Env Variable
      run: |
        # Check if the current branch ends with the the preview branch
        if ( "${{ github.ref }}" -match "preview/v1.0.0-preview.1$") {
            echo "MY_VAR=It Is Preview" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        } else {
            echo "MY_VAR=It Is Not Preview" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        }

    - name: Get Version From Project File
      run: echo "${{ env.MY_VAR }}"
