name: 🧪 Workflow Testing 🧪

env:
  if: ${{ github.ref == 'preview/v1.0.0-preview.1' }}
  MY_VAR: IsPreview

  if: ${{ github.ref != 'preview/v1.0.0-preview.1' }}
  MY_VAR: IsNotPreview

on:
  workflow_dispatch:
  push:
    branches: [ preview/v1.0.0-preview.1 ]

jobs:
  Test_Job:
    name: Test Job
    runs-on: windows-latest
    # environment: preview # TODO: Test this with variable values and if expressions
    steps:
    - name: Print Branch Name
      run: echo "Branch - ${{ github.ref }}"

    - name: Get Version From Project File
      run: echo "${{ env.MY_VAR }}"
