name: 🧪 Workflow Testing 🧪

env:
  MY_VAR: OriginalValue

on:
  workflow_dispatch:
  push:
    branches: [ preview/v1.0.0-preview.1 ]

jobs:
  Test_Job:
    name: Test Job
    runs-on: windows-latest
    # environment: preview # TODO: Test this with variable values and if expressions
    steps:
    - name: Get Version From Project File
      run: echo "${{ env.MY_VAR }}"
